
SERVICES = ['messaging']

# Messaging service configuration
MESSAGING_HOST = ''
MESSAGING_PORT = 1126
MESSAGING_PROTOCOL = 'SMAP'
MESSAGING_MAX_PENDING_CLIENTS = 8
MESSAGING_WAIT_INTERVAL = 0.1
MESSAGING_BUFFER_SIZE = 4096

# Deposit service configuration
DEPOSIT_HOST = ''
DEPOSIT_PORT = 1999
DEPOSIT_PROTOCOL = 'HTTP'
DEPOSIT_MAX_PENDING_CLIENTS = 4
